integer myDivisor = 10;
integer myReciprocal = 0;
double myReminder;
try {
    myReminder = myDivisor/myReciprocal;
   	system.debug(myReminder);
    
}
// catch get/identify the error 'exception' is generic 
catch (Exception e){
    // 'e' gives the exception/error message
    System.debug(e);
    
}

// 'MathException' is not generic it will get only errors associated with 'MathException'
/*catch (MathException e){
    // 'e' gives the exception/error message
    System.debug(e);
    
}*/
// finally will get execuated no matters what.
finally{
    myReciprocal ++;
    myReminder = myDivisor/myReciprocal;
    system.debug(myReminder);
}
